# Generated by Django 5.1 on 2024-12-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='id_productos',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productos',
            name='id_proveedor',
            field=models.IntegerField(),
        ),
    ]
