# Generated by Django 5.1 on 2024-12-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('id_detalles', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('id_orden', models.IntegerField()),
                ('id_producto', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('descuento', models.FloatField()),
            ],
        ),
    ]
