# Generated by Django 5.1 on 2024-12-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('id_detalles', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('id_orden', models.IntegerField(max_length=6)),
                ('id_empleado', models.IntegerField(max_length=6)),
                ('direccion_envio', models.TextField()),
                ('entregado', models.BooleanField()),
            ],
        ),
    ]
