# Generated by Django 5.1 on 2024-12-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalles_ordenes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles',
            name='id_empleado',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detalles',
            name='id_orden',
            field=models.IntegerField(),
        ),
    ]
