# Generated by Django 5.1 on 2024-12-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('fecha_registro', models.DateField()),
            ],
        ),
    ]
