# Generated by Django 5.1.3 on 2024-12-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id_orden', models.IntegerField(primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField()),
                ('id_empleado', models.IntegerField()),
                ('id_producto', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('fecha_orden', models.DateField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
