# Generated by Django 5.1 on 2024-12-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id_orden', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField()),
                ('fecha_orden', models.DateField()),
                ('total', models.FloatField()),
                ('estado', models.CharField(max_length=100)),
                ('metodo_pago', models.CharField(max_length=100)),
                ('comentarios', models.TextField()),
            ],
        ),
    ]
