# Generated by Django 5.1.3 on 2024-11-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_clientes', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.TextField()),
                ('fecha_reg', models.DateField()),
            ],
        ),
    ]
